/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule


module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Cont (
  input A5,
  input A4,
  input A3,
  input A2,
  input A1,
  input A0,
  input AnotS,
  input CLK,
  output LED
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire LED_temp;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  assign s0 = (A0 ^ AnotS);
  assign s1 = (A1 ^ AnotS);
  assign s2 = (A2 ^ AnotS);
  assign s3 = (A3 ^ AnotS);
  assign s4 = (A4 ^ AnotS);
  assign s5 = (A5 ^ AnotS);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( LED_temp ),
    .b( s5 ),
    .c_i( s6 ),
    .s( s7 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i1 (
    .a( s8 ),
    .b( s4 ),
    .c_i( s9 ),
    .s( s10 ),
    .c_o( s6 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( s11 ),
    .b( s3 ),
    .c_i( s12 ),
    .s( s13 ),
    .c_o( s9 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i3 (
    .a( s14 ),
    .b( s2 ),
    .c_i( s15 ),
    .s( s16 ),
    .c_o( s12 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i4 (
    .a( s17 ),
    .b( s1 ),
    .c_i( s18 ),
    .s( s19 ),
    .c_o( s15 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i5 (
    .a( s20 ),
    .b( s0 ),
    .c_i( AnotS ),
    .s( s21 ),
    .c_o( s18 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s21 ),
    .C( CLK ),
    .Q( s20 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s19 ),
    .C( CLK ),
    .Q( s17 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( s16 ),
    .C( CLK ),
    .Q( s14 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s13 ),
    .C( CLK ),
    .Q( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i10 (
    .D( s10 ),
    .C( CLK ),
    .Q( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( s7 ),
    .C( CLK ),
    .Q( LED_temp )
  );
  assign LED = LED_temp;
endmodule
